export const DataExplorer = [
  { id: 1, title: 'Diagram Static', avatar: 'D', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '4', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 2, title: 'Audit', avatar: 'A', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '5', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 3, title: 'Benchmark', avatar: 'B', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '5', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 4, title: 'Contract', avatar: 'C', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '5', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 5, title: 'Despatch Order', avatar: 'DO', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '5', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 6, title: 'Invoice', avatar: 'I', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '5', badge2: '10', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  { id: 7, title: 'Invoice Batch Processing', avatar: 'IB', subheader: 'September 14, 2020', content: 'This impressive mining market ', badge1: '10', badge2: '5', collapseTitle: 'Method:', collapseContent: 'Heat 1/2 cup of the broth in a pot until simmering, add saffron and set aside for 10' },
  // { id: 8, title: 'Payment', avatar: 'P', subheader: 'December 1, 2025', content: '', badge1: '6', badge2: '1', collapseTitle: '', collapseContent: '' },
  // { id: 9, title: 'Currency Exchange', avatar: 'CE', subheader: 'December 1, 2025', content: '8', badge1: '', badge2: '34', collapseTitle: '', collapseContent: '' },
  // { id: 10, title: 'Pricing', avatar: 'P', subheader: 'December 1, 2025', content: '', badge1: '1', badge2: '2', collapseTitle: '', collapseContent: '' },
  // { id: 11, title: 'Hedging', avatar: 'H', subheader: 'December 1, 2025', content: '3', badge1: '', badge2: '5', collapseTitle: '', collapseContent: '' },
  // { id: 12, title: 'Transaction', avatar: 'T', subheader: 'December 1, 2025', content: '', badge1: '12', badge2: '6', collapseTitle: '', collapseContent: '' },
  // { id: 13, title: 'Sample', avatar: 'S', subheader: 'December 1, 2025', content: '', badge1: '22', badge2: '6', collapseTitle: '', collapseContent: '' },
  // { id: 14, title: 'Shipment', avatar: 'SP', subheader: 'December 1, 2025', content: '', badge1: '5', badge2: '6', collapseTitle: '', collapseContent: '' },
  // { id: 15, title: 'Train', avatar: 'T', subheader: 'December 1, 2025', content: '', badge1: '7', badge2: '90', collapseTitle: '', collapseContent: '' },
  // { id: 16, title: 'Barge', avatar: 'B', subheader: 'December 1, 2025', content: '', badge1: '0', badge2: '6', collapseTitle: '', collapseContent: '' },
  // { id: 17, title: 'Truck Despatch', avatar: 'TD', subheader: 'December 1, 2025', content: '', badge1: '34', badge2: '6', collapseTitle: '', collapseContent: '' },
  // { id: 18, title: 'Lot Despatch', avatar: 'LD', subheader: 'December 1, 2025', content: '', badge1: '3', badge2: '3', collapseTitle: '', collapseContent: '' },
  // { id: 19, title: 'Supply Train', avatar: 'ST', subheader: 'December 1, 2025', content: '', badge1: '4', badge2: '3', collapseTitle: '', collapseContent: '' },
  // { id: 20, title: 'Supply Ship', avatar: 'SS', subheader: 'December 1, 2025', content: '', badge1: '8', badge2: '23', collapseTitle: '', collapseContent: '' },
  // { id: 21, title: 'Ship and Barge Lineup', avatar: 'SB', subheader: 'December 1, 2025', content: '', badge1: '89', badge2: '2', collapseTitle: '', collapseContent: '' },
  // { id: 22, title: 'Barge Lineup', avatar: 'BL', subheader: 'December 1, 2025', content: '', badge1: '89', badge2: '3', collapseTitle: '', collapseContent: '' },
]