export { default as Dashboard } from './Dashboard'
export { default as NavigationDrawer } from './NavigationDrawer'
export { default as PermanentDrawer } from './NavigationDrawer'
export { default as UnitMeasurement } from './UnitMeasurement'
export { default as Login } from './PageLogin'
export { default as PageRouter } from './PageRouter'
export { default as SupplyChain } from './SupplyChain'
export { default as Tabs } from './Tabs'
export { default as Reporting } from './Reporting'
export { default as ChartLine } from './Chart'
// export { default as ChartBar } from './Chart'
export { default as Barge } from './Barge'
export { default as Explorer } from './Explorer'
export { default as Keyboard } from './Keyboard'
export { default as Helpers } from './Helpers'
export { default as Invoices } from './Invoices'
export { default as Payment } from './Payment'

// avatar
export { MarryDoe } from './Profiles'
export { JohnDoe } from './Profiles'
export { JohnnyWalker } from './Profiles'
export { BlackLabel } from './Profiles'
export { Jocker } from './Profiles'
export { Batman } from './Profiles'